# Form implementation generated from reading ui file 'd:\Ebba\Dokument\Examensarbete\Kod\Git\hockey-statistik\Python\main_ui_window.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 390)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(24)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QPushButton {\n"
"    \n"
"    font: 75 16pt \"MS Shell Dlg 2\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonConnectToDB = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonConnectToDB.setObjectName("pushButtonConnectToDB")
        self.verticalLayout.addWidget(self.pushButtonConnectToDB)
        self.pushButtonAddData = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddData.setStyleSheet("QPushButton")
        self.pushButtonAddData.setObjectName("pushButtonAddData")
        self.verticalLayout.addWidget(self.pushButtonAddData)
        self.pushButtonTopTen = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonTopTen.setStyleSheet("QPushbutton{\n"
"border-radius: 25 px;\n"
"background-color:rgb(85, 170, 255);\n"
"color:rgb(85, 85, 255);\n"
"}\n"
"\n"
"QPushbutton:hover{\n"
"background-color:rgb(50, 110, 255);\n"
"color:rgb(255,255, 255);\n"
"}\n"
"\n"
"QPushbutton:pressed{\n"
"background-color:rgb(100, 170, 255);\n"
"}")
        self.pushButtonTopTen.setObjectName("pushButtonTopTen")
        self.verticalLayout.addWidget(self.pushButtonTopTen)
        self.pushButtonSearchDB = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonSearchDB.setFont(font)
        self.pushButtonSearchDB.setObjectName("pushButtonSearchDB")
        self.verticalLayout.addWidget(self.pushButtonSearchDB)
        self.pushButtonDisconnectFromDB = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDisconnectFromDB.setObjectName("pushButtonDisconnectFromDB")
        self.verticalLayout.addWidget(self.pushButtonDisconnectFromDB)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tableWidgetTopTen = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetTopTen.setRowCount(10)
        self.tableWidgetTopTen.setColumnCount(2)
        self.tableWidgetTopTen.setObjectName("tableWidgetTopTen")
        self.horizontalLayout.addWidget(self.tableWidgetTopTen)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(300, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonConnectToDB.setText(_translate("MainWindow", "ConnectToDB"))
        self.pushButtonAddData.setText(_translate("MainWindow", "Get top 10 Teams"))
        self.pushButtonTopTen.setText(_translate("MainWindow", "Get top 10 players"))
        self.pushButtonSearchDB.setText(_translate("MainWindow", "Get top 10 events"))
        self.pushButtonDisconnectFromDB.setText(_translate("MainWindow", "DisconnectFromDB"))
