# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'calculator.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLineEdit, QSizePolicy, QToolButton,
    QWidget)

class Ui_Calculator(object):
    def setupUi(self, Calculator):
        if not Calculator.objectName():
            Calculator.setObjectName(u"Calculator")
        Calculator.resize(314, 301)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Calculator.sizePolicy().hasHeightForWidth())
        Calculator.setSizePolicy(sizePolicy)
        Calculator.setMinimumSize(QSize(314, 301))
        Calculator.setMaximumSize(QSize(314, 301))
        self.backspaceButton = QToolButton(Calculator)
        self.backspaceButton.setObjectName(u"backspaceButton")
        self.backspaceButton.setGeometry(QRect(10, 50, 91, 41))
        self.clearButton = QToolButton(Calculator)
        self.clearButton.setObjectName(u"clearButton")
        self.clearButton.setGeometry(QRect(110, 50, 91, 41))
        self.clearAllButton = QToolButton(Calculator)
        self.clearAllButton.setObjectName(u"clearAllButton")
        self.clearAllButton.setGeometry(QRect(210, 50, 91, 41))
        self.clearMemoryButton = QToolButton(Calculator)
        self.clearMemoryButton.setObjectName(u"clearMemoryButton")
        self.clearMemoryButton.setGeometry(QRect(10, 100, 41, 41))
        self.readMemoryButton = QToolButton(Calculator)
        self.readMemoryButton.setObjectName(u"readMemoryButton")
        self.readMemoryButton.setGeometry(QRect(10, 150, 41, 41))
        self.setMemoryButton = QToolButton(Calculator)
        self.setMemoryButton.setObjectName(u"setMemoryButton")
        self.setMemoryButton.setGeometry(QRect(10, 200, 41, 41))
        self.addToMemoryButton = QToolButton(Calculator)
        self.addToMemoryButton.setObjectName(u"addToMemoryButton")
        self.addToMemoryButton.setGeometry(QRect(10, 250, 41, 41))
        self.sevenButton = QToolButton(Calculator)
        self.sevenButton.setObjectName(u"sevenButton")
        self.sevenButton.setGeometry(QRect(60, 100, 41, 41))
        self.eightButton = QToolButton(Calculator)
        self.eightButton.setObjectName(u"eightButton")
        self.eightButton.setGeometry(QRect(110, 100, 41, 41))
        self.nineButton = QToolButton(Calculator)
        self.nineButton.setObjectName(u"nineButton")
        self.nineButton.setGeometry(QRect(160, 100, 41, 41))
        self.fourButton = QToolButton(Calculator)
        self.fourButton.setObjectName(u"fourButton")
        self.fourButton.setGeometry(QRect(60, 150, 41, 41))
        self.fiveButton = QToolButton(Calculator)
        self.fiveButton.setObjectName(u"fiveButton")
        self.fiveButton.setGeometry(QRect(110, 150, 41, 41))
        self.sixButton = QToolButton(Calculator)
        self.sixButton.setObjectName(u"sixButton")
        self.sixButton.setGeometry(QRect(160, 150, 41, 41))
        self.oneButton = QToolButton(Calculator)
        self.oneButton.setObjectName(u"oneButton")
        self.oneButton.setGeometry(QRect(60, 200, 41, 41))
        self.twoButton = QToolButton(Calculator)
        self.twoButton.setObjectName(u"twoButton")
        self.twoButton.setGeometry(QRect(110, 200, 41, 41))
        self.threeButton = QToolButton(Calculator)
        self.threeButton.setObjectName(u"threeButton")
        self.threeButton.setGeometry(QRect(160, 200, 41, 41))
        self.zeroButton = QToolButton(Calculator)
        self.zeroButton.setObjectName(u"zeroButton")
        self.zeroButton.setGeometry(QRect(60, 250, 41, 41))
        self.pointButton = QToolButton(Calculator)
        self.pointButton.setObjectName(u"pointButton")
        self.pointButton.setGeometry(QRect(110, 250, 41, 41))
        self.changeSignButton = QToolButton(Calculator)
        self.changeSignButton.setObjectName(u"changeSignButton")
        self.changeSignButton.setGeometry(QRect(160, 250, 41, 41))
        self.plusButton = QToolButton(Calculator)
        self.plusButton.setObjectName(u"plusButton")
        self.plusButton.setGeometry(QRect(210, 250, 41, 41))
        self.divisionButton = QToolButton(Calculator)
        self.divisionButton.setObjectName(u"divisionButton")
        self.divisionButton.setGeometry(QRect(210, 100, 41, 41))
        self.timesButton = QToolButton(Calculator)
        self.timesButton.setObjectName(u"timesButton")
        self.timesButton.setGeometry(QRect(210, 150, 41, 41))
        self.minusButton = QToolButton(Calculator)
        self.minusButton.setObjectName(u"minusButton")
        self.minusButton.setGeometry(QRect(210, 200, 41, 41))
        self.squareRootButton = QToolButton(Calculator)
        self.squareRootButton.setObjectName(u"squareRootButton")
        self.squareRootButton.setGeometry(QRect(260, 100, 41, 41))
        self.powerButton = QToolButton(Calculator)
        self.powerButton.setObjectName(u"powerButton")
        self.powerButton.setGeometry(QRect(260, 150, 41, 41))
        self.reciprocalButton = QToolButton(Calculator)
        self.reciprocalButton.setObjectName(u"reciprocalButton")
        self.reciprocalButton.setGeometry(QRect(260, 200, 41, 41))
        self.equalButton = QToolButton(Calculator)
        self.equalButton.setObjectName(u"equalButton")
        self.equalButton.setGeometry(QRect(260, 250, 41, 41))
        self.display = QLineEdit(Calculator)
        self.display.setObjectName(u"display")
        self.display.setGeometry(QRect(10, 10, 291, 31))
        self.display.setMaxLength(15)
        self.display.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.display.setReadOnly(True)

        self.retranslateUi(Calculator)

        QMetaObject.connectSlotsByName(Calculator)
    # setupUi

    def retranslateUi(self, Calculator):
        Calculator.setWindowTitle(QCoreApplication.translate("Calculator", u"Calculator", None))
        self.backspaceButton.setText(QCoreApplication.translate("Calculator", u"Backspace", None))
        self.clearButton.setText(QCoreApplication.translate("Calculator", u"Clear", None))
        self.clearAllButton.setText(QCoreApplication.translate("Calculator", u"Clear All", None))
        self.clearMemoryButton.setText(QCoreApplication.translate("Calculator", u"MC", None))
        self.readMemoryButton.setText(QCoreApplication.translate("Calculator", u"MR", None))
        self.setMemoryButton.setText(QCoreApplication.translate("Calculator", u"MS", None))
        self.addToMemoryButton.setText(QCoreApplication.translate("Calculator", u"M+", None))
        self.sevenButton.setText(QCoreApplication.translate("Calculator", u"7", None))
        self.eightButton.setText(QCoreApplication.translate("Calculator", u"8", None))
        self.nineButton.setText(QCoreApplication.translate("Calculator", u"9", None))
        self.fourButton.setText(QCoreApplication.translate("Calculator", u"4", None))
        self.fiveButton.setText(QCoreApplication.translate("Calculator", u"5", None))
        self.sixButton.setText(QCoreApplication.translate("Calculator", u"6", None))
        self.oneButton.setText(QCoreApplication.translate("Calculator", u"1", None))
        self.twoButton.setText(QCoreApplication.translate("Calculator", u"2", None))
        self.threeButton.setText(QCoreApplication.translate("Calculator", u"3", None))
        self.zeroButton.setText(QCoreApplication.translate("Calculator", u"0", None))
        self.pointButton.setText(QCoreApplication.translate("Calculator", u".", None))
        self.changeSignButton.setText(QCoreApplication.translate("Calculator", u"+-", None))
        self.plusButton.setText(QCoreApplication.translate("Calculator", u"+", None))
        self.divisionButton.setText(QCoreApplication.translate("Calculator", u"/", None))
        self.timesButton.setText(QCoreApplication.translate("Calculator", u"*", None))
        self.minusButton.setText(QCoreApplication.translate("Calculator", u"-", None))
        self.squareRootButton.setText(QCoreApplication.translate("Calculator", u"Sqrt", None))
        self.powerButton.setText(QCoreApplication.translate("Calculator", u"x^2", None))
        self.reciprocalButton.setText(QCoreApplication.translate("Calculator", u"1/x", None))
        self.equalButton.setText(QCoreApplication.translate("Calculator", u"=", None))
    # retranslateUi

